version: "3.9"

services:
  webapp:
    build: .
    ports:
      - "8080:8080"
  chrome:
    image: "selenium/standalone-chrome"
    ports:
      - "4444:4444"
    shm_size: "2gb"
    depends_on:
      - webapp
